name: "test"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: test
        with:
          minimum-version: 2018.4
          maximum-version: 2019.4
          append-versions: |
            2020.3.46f1
            2021.3.21f1
      - if: steps.unity-changeset.outputs.test != '[]'
        run: |
          echo '::error changeset value is not correct, ${{ steps.unity-changeset.outputs.changeset }}'
          exit 1
